<template>
	<view>
		<view :class="['certmain',index%2?'':'certmainb']" :key="index" v-for="(item,index) in data.data.vaccineRecordGroupList">
			<view class="certmain_title">{{item.vaccinationAge}}</view>
			<view class="certmain_box" :key="idx" v-for="(itm,idx) in item.vaccineRecordDetailList">
				<van-button size="mini" color="#4BD2B6">免费</van-button>
				<text class="linemain">{{itm.name}}</text>
				<text></text>
				<text></text>
			</view>
		</view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				data: {
					"code":"0000",
					"responseMsg":"查询成功",
					"data":{
						"vaccineRecordGroupList":[
							{
								"vaccinationAge":"出生",
								"monthNumS":0,
								"vaccineRecordDetailList":[
									{
										"name":"乙肝疫苗",
										"freeStatus":1,
										"monthNumS":0,
										"currTimes":1,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"卡介苗",
										"freeStatus":1,
										"monthNumS":0,
										"currTimes":1,
										"totalTimes":1,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"1月龄",
								"monthNumS":1,
								"vaccineRecordDetailList":[
									{
										"name":"乙肝疫苗",
										"freeStatus":1,
										"monthNumS":1,
										"currTimes":2,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"5价轮状病毒疫苗 ",
										"freeStatus":2,
										"monthNumS":1,
										"currTimes":1,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"2月龄",
								"monthNumS":2,
								"vaccineRecordDetailList":[
									{
										"name":"5价轮状病毒疫苗 ",
										"freeStatus":2,
										"monthNumS":2,
										"currTimes":2,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"单价轮状病毒疫苗",
										"freeStatus":2,
										"monthNumS":2,
										"currTimes":1,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"五联疫苗",
										"freeStatus":2,
										"monthNumS":2,
										"currTimes":1,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"13价肺炎结合疫苗",
										"freeStatus":2,
										"monthNumS":2,
										"currTimes":1,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"Hib结合疫苗",
										"freeStatus":2,
										"monthNumS":2,
										"currTimes":1,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"脊灰灭活疫苗(1)",
										"freeStatus":1,
										"monthNumS":2,
										"currTimes":1,
										"totalTimes":1,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"3月龄",
								"monthNumS":3,
								"vaccineRecordDetailList":[
									{
										"name":"5价轮状病毒疫苗 ",
										"freeStatus":2,
										"monthNumS":3,
										"currTimes":3,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"四联疫苗",
										"freeStatus":2,
										"monthNumS":3,
										"currTimes":1,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"五联疫苗",
										"freeStatus":2,
										"monthNumS":3,
										"currTimes":2,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"13价肺炎结合疫苗",
										"freeStatus":2,
										"monthNumS":3,
										"currTimes":2,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"脊灰灭活疫苗(2)",
										"freeStatus":1,
										"monthNumS":3,
										"currTimes":1,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"百白破疫苗",
										"freeStatus":1,
										"monthNumS":3,
										"currTimes":1,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"Hib结合疫苗",
										"freeStatus":2,
										"monthNumS":3,
										"currTimes":2,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"脊灰减毒疫苗",
										"freeStatus":1,
										"monthNumS":3,
										"currTimes":1,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"4月龄",
								"monthNumS":4,
								"vaccineRecordDetailList":[
									{
										"name":"百白破疫苗",
										"freeStatus":1,
										"monthNumS":4,
										"currTimes":2,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"脊灰减毒疫苗",
										"freeStatus":1,
										"monthNumS":4,
										"currTimes":2,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"Hib结合疫苗",
										"freeStatus":2,
										"monthNumS":4,
										"currTimes":3,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"13价肺炎结合疫苗",
										"freeStatus":2,
										"monthNumS":4,
										"currTimes":3,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"五联疫苗",
										"freeStatus":2,
										"monthNumS":4,
										"currTimes":3,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"脊灰灭活疫苗(2)",
										"freeStatus":1,
										"monthNumS":4,
										"currTimes":2,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"四联疫苗",
										"freeStatus":2,
										"monthNumS":4,
										"currTimes":2,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"5月龄",
								"monthNumS":5,
								"vaccineRecordDetailList":[
									{
										"name":"百白破疫苗",
										"freeStatus":1,
										"monthNumS":5,
										"currTimes":3,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"四联疫苗",
										"freeStatus":2,
										"monthNumS":5,
										"currTimes":3,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"6月龄",
								"monthNumS":6,
								"vaccineRecordDetailList":[
									{
										"name":"乙肝疫苗",
										"freeStatus":1,
										"monthNumS":6,
										"currTimes":3,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"A群流脑多糖疫苗",
										"freeStatus":1,
										"monthNumS":6,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"EV71手足口疫苗",
										"freeStatus":2,
										"monthNumS":6,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"AC-Hib三联疫苗",
										"freeStatus":2,
										"monthNumS":6,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"AC群流脑结合疫苗",
										"freeStatus":2,
										"monthNumS":6,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"3价流感疫苗",
										"freeStatus":2,
										"monthNumS":6,
										"currTimes":1,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"7月龄",
								"monthNumS":7,
								"vaccineRecordDetailList":[
									{
										"name":"EV71手足口疫苗",
										"freeStatus":2,
										"monthNumS":7,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"3价流感疫苗",
										"freeStatus":2,
										"monthNumS":7,
										"currTimes":1,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"8月龄",
								"monthNumS":8,
								"vaccineRecordDetailList":[
									{
										"name":"麻风疫苗",
										"freeStatus":1,
										"monthNumS":8,
										"currTimes":1,
										"totalTimes":1,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"乙脑灭活疫苗",
										"freeStatus":2,
										"monthNumS":8,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"乙脑减毒疫苗",
										"freeStatus":1,
										"monthNumS":8,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"9月龄",
								"monthNumS":9,
								"vaccineRecordDetailList":[
									{
										"name":"A群流脑多糖疫苗",
										"freeStatus":1,
										"monthNumS":9,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"AC-Hib三联疫苗",
										"freeStatus":2,
										"monthNumS":9,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"AC群流脑结合疫苗",
										"freeStatus":2,
										"monthNumS":9,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"12月龄",
								"monthNumS":12,
								"vaccineRecordDetailList":[
									{
										"name":"13价肺炎结合疫苗",
										"freeStatus":2,
										"monthNumS":12,
										"currTimes":4,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"水痘疫苗",
										"freeStatus":2,
										"monthNumS":12,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"14月龄",
								"monthNumS":14,
								"vaccineRecordDetailList":[
									{
										"name":"单价轮状病毒疫苗",
										"freeStatus":2,
										"monthNumS":14,
										"currTimes":2,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"18~24月龄",
								"monthNumS":18,
								"vaccineRecordDetailList":[
									{
										"name":"百白破疫苗",
										"freeStatus":1,
										"monthNumS":18,
										"currTimes":4,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"18月龄",
								"monthNumS":18,
								"vaccineRecordDetailList":[
									{
										"name":"甲肝灭活疫苗",
										"freeStatus":2,
										"monthNumS":18,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"甲肝减毒疫苗",
										"freeStatus":1,
										"monthNumS":18,
										"currTimes":1,
										"totalTimes":1,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"麻腮风疫苗",
										"freeStatus":1,
										"monthNumS":18,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"五联疫苗",
										"freeStatus":2,
										"monthNumS":18,
										"currTimes":4,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"四联疫苗",
										"freeStatus":2,
										"monthNumS":18,
										"currTimes":4,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"3价流感疫苗",
										"freeStatus":2,
										"monthNumS":18,
										"currTimes":1,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"Hib结合疫苗",
										"freeStatus":2,
										"monthNumS":18,
										"currTimes":4,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"2周岁",
								"monthNumS":24,
								"vaccineRecordDetailList":[
									{
										"name":"乙脑减毒疫苗",
										"freeStatus":1,
										"monthNumS":24,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"乙脑灭活疫苗",
										"freeStatus":2,
										"monthNumS":24,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"23价肺炎多糖疫苗",
										"freeStatus":2,
										"monthNumS":24,
										"currTimes":1,
										"totalTimes":1,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"甲肝灭活疫苗",
										"freeStatus":2,
										"monthNumS":24,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"26月龄",
								"monthNumS":26,
								"vaccineRecordDetailList":[
									{
										"name":"单价轮状病毒疫苗",
										"freeStatus":2,
										"monthNumS":26,
										"currTimes":3,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"30月龄",
								"monthNumS":30,
								"vaccineRecordDetailList":[
									{
										"name":"3价流感疫苗",
										"freeStatus":2,
										"monthNumS":30,
										"currTimes":1,
										"totalTimes":4,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"3周岁",
								"monthNumS":36,
								"vaccineRecordDetailList":[
									{
										"name":"4价流感疫苗",
										"freeStatus":2,
										"monthNumS":36,
										"currTimes":1,
										"totalTimes":7,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"4价流脑多糖疫苗",
										"freeStatus":2,
										"monthNumS":36,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"AC群流脑多糖疫苗",
										"freeStatus":1,
										"monthNumS":36,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"4~6周岁",
								"monthNumS":48,
								"vaccineRecordDetailList":[
									{
										"name":"腮腺炎疫苗",
										"freeStatus":2,
										"monthNumS":48,
										"currTimes":1,
										"totalTimes":1,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"4周岁",
								"monthNumS":48,
								"vaccineRecordDetailList":[
									{
										"name":"4价流感疫苗",
										"freeStatus":2,
										"monthNumS":48,
										"currTimes":2,
										"totalTimes":7,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"水痘疫苗",
										"freeStatus":2,
										"monthNumS":48,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"脊灰灭活疫苗(2)",
										"freeStatus":1,
										"monthNumS":48,
										"currTimes":3,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"脊灰减毒疫苗",
										"freeStatus":1,
										"monthNumS":48,
										"currTimes":3,
										"totalTimes":3,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"5周岁",
								"monthNumS":60,
								"vaccineRecordDetailList":[
									{
										"name":"4价流感疫苗",
										"freeStatus":2,
										"monthNumS":60,
										"currTimes":3,
										"totalTimes":7,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"6周岁",
								"monthNumS":72,
								"vaccineRecordDetailList":[
									{
										"name":"4价流脑多糖疫苗",
										"freeStatus":2,
										"monthNumS":72,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"AC群流脑多糖疫苗",
										"freeStatus":1,
										"monthNumS":72,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"4价流感疫苗",
										"freeStatus":2,
										"monthNumS":72,
										"currTimes":4,
										"totalTimes":7,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"麻腮风疫苗",
										"freeStatus":1,
										"monthNumS":72,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"白破疫苗",
										"freeStatus":1,
										"monthNumS":72,
										"currTimes":1,
										"totalTimes":1,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"7周岁",
								"monthNumS":84,
								"vaccineRecordDetailList":[
									{
										"name":"4价流感疫苗",
										"freeStatus":2,
										"monthNumS":84,
										"currTimes":5,
										"totalTimes":7,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"8周岁",
								"monthNumS":96,
								"vaccineRecordDetailList":[
									{
										"name":"4价流感疫苗",
										"freeStatus":2,
										"monthNumS":96,
										"currTimes":6,
										"totalTimes":7,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"9周岁",
								"monthNumS":108,
								"vaccineRecordDetailList":[
									{
										"name":"2价HPV疫苗",
										"freeStatus":2,
										"monthNumS":108,
										"currTimes":1,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									},
									{
										"name":"4价流感疫苗",
										"freeStatus":2,
										"monthNumS":108,
										"currTimes":7,
										"totalTimes":7,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							},
							{
								"vaccinationAge":"9.5周岁",
								"monthNumS":114,
								"vaccineRecordDetailList":[
									{
										"name":"2价HPV疫苗",
										"freeStatus":2,
										"monthNumS":114,
										"currTimes":2,
										"totalTimes":2,
										"vaccinationDate":null,
										"vaccinationStatus":null
									}
								]
							}
						]
					}
				}
			};
		},
		mounted() {
			
		},
		methods: {
			changePage(val) {
				this.isShow = val;
			},
		}
	}
</script>

<style lang="less">
.certmain{
	padding: 30rpx;
	background: #fff;
	.certmain_title{
		color: #666666;
		font-size: 26rpx;
	}
	.certmain_box{
		color: #666666;
		font-size: 30rpx;
		line-height: 70rpx;
		.linemain{
			margin-left: 30rpx;
		}
	}
}
.certmainb{
	background: #FAFAFB;
}
</style>
